name       : libxcb
version    : '1.15'
release    : 31
source     :
    - https://www.x.org/releases/individual/xcb/libxcb-1.15.tar.gz : 1cb65df8543a69ec0555ac696123ee386321dfac1964a3da39976c9a05ad724d
license    : MIT
component  : xorg.library
summary    : X C Binding
description: |
    The libxcb package provides an interface to the X Window System protocol, which replaces the current Xlib interface. Xlib can also use XCB as a transport layer, allowing software to make requests and receive responses with both.
emul32     : yes
optimize   : speed
mancompress : yes
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xdmcp)
    - pkgconfig(xcb-proto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    sed -i configure.ac -e 's/pthread\-stubs//'
    %reconfigure --enable-xinput \
               --disable-static \
               --enable-xprint=yes \
               --enable-xevie=yes \
               --enable-dri3=yes \
               --docdir=/usr/share/doc/libxcb-1.11
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
