name       : libxcb
version    : '1.13'
release    : 18
source     :
    - https://www.x.org/releases/individual/xcb/libxcb-1.13.tar.gz : 0bb3cfd46dbd90066bf4d7de3cad73ec1024c7325a4a0cbf5f4a0d4fa91155fb
license    :
    - MIT
summary    : X C Binding
component  : xorg.library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xdmcp)
    - pkgconfig(xcb-proto)
    - pkgconfig(xproto)
    - pkgconfig(xorg-macros)
    - check
emul32     : yes
optimize   : speed
description: |
    The libxcb package provides an interface to the X Window System protocol, which replaces the current Xlib interface. Xlib can also use XCB as a transport layer, allowing software to make requests and receive responses with both.
setup      : |
    sed -i configure.ac -e 's/pthread\-stubs//'
    autoreconf -fi
    %configure --prefix=/usr \
               --enable-xinput \
               --disable-static \
               --enable-xprint=yes \
               --enable-xevie=yes \
               --enable-dri3=yes \
               --docdir=/usr/share/doc/libxcb-1.11
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check