name        : libxcb
version     : 1.11.1
release     : 10
source      :
    - http://xcb.freedesktop.org/dist/libxcb-1.11.1.tar.gz : 660312d5e64d0a5800262488042c1707a0261fa01a759bad265b1b75dd4844dd
license     :
    - MIT
summary     : X C Binding
builddeps   :
    - pkgconfig(xcb-proto)
    - pkgconfig(xproto)
    - pkgconfig(xau)
    - pkgconfig32(xau)
    - pkgconfig(xorg-macros)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    The libxcb package provides an interface to the X Window System protocol, which replaces the current Xlib interface. Xlib can also use XCB as a transport layer, allowing software to make requests and receive responses with both.
setup      : |
    sed -i configure.ac -e 's/pthread\-stubs//'
    autoreconf -fi
    %configure --prefix=/usr \
               --enable-xinput \
               --disable-static \
               --docdir=/usr/share/doc/libxcb-1.11
build      : |
    %make
install    : |
    %make_install
    %make clean
