name       : libxcb
version    : 1.13.1
release    : 21
source     :
    - https://www.x.org/releases/individual/xcb/libxcb-1.13.1.tar.gz : f09a76971437780a602303170fd51b5f7474051722bc39d566a272d2c4bde1b5
license    : MIT
component  : xorg.library
summary    : X C Binding
description: |
    The libxcb package provides an interface to the X Window System protocol, which replaces the current Xlib interface. Xlib can also use XCB as a transport layer, allowing software to make requests and receive responses with both.
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xdmcp)
    - pkgconfig(xcb-proto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
emul32     : yes
optimize   : speed
setup      : |
    sed -i configure.ac -e 's/pthread\-stubs//'
    %reconfigure --enable-xinput \
               --disable-static \
               --enable-xprint=yes \
               --enable-xevie=yes \
               --enable-dri3=yes \
               --docdir=/usr/share/doc/libxcb-1.11
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
